# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# 워크플로우 이름: iOS CI
name: iOS CI

# 트리거: main 브랜치 푸시 및 PR 이벤트
on:
  push:
    branches:
      - main                # main 브랜치에 푸시되면 실행
  pull_request:
    types: [opened, synchronize, reopened]  # PR 생성·동기화·재오픈 시 실행

# 잡 정의
jobs:
  build:
    # 러너: 최신 macOS 환경 사용
    runs-on: macos-latest

    steps:
      # 단계 1: 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
      # 단계 2: Xcode 설치 및 선택
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      # 단계 3: Swift 패키지 의존성 해결
      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies

      # 단계 4: iOS 시뮬레이터 클린 빌드
      - name: Build
        run: |
          xcodebuild clean build \
            -project NetworkingStudy.xcodeproj \
            -scheme NetworkingStudy \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.0'

      # 단계 5: 시뮬레이터에서 단위 테스트 실행
      - name: Run tests
        run: |
          xcodebuild test \
            -project NetworkingStudy.xcodeproj \
            -scheme NetworkingStudy \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.0'